// src/app/reset-password/page.tsx
'use client'

import { useState, useEffect, Suspense } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { useNotifications } from '../../components/NotificationSystem'

function ResetPasswordContent() {
  const [newPassword, setNewPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [tokenValid, setTokenValid] = useState(false)
  const [verifying, setVerifying] = useState(true)
  const router = useRouter()
  const searchParams = useSearchParams()
  const { addNotification } = useNotifications()

  useEffect(() => {
    const token = searchParams.get('token')
    if (token) {
      verifyToken(token)
    } else {
      setVerifying(false)
      addNotification({
        type: 'error',
        title: 'خطأ',
        message: 'رابط إعادة التعيين غير صحيح'
      })
    }
  }, [searchParams])

  const verifyToken = async (token: string) => {
    try {
      const response = await fetch('/api/auth/verify-reset', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ token }),
      })

      if (response.ok) {
        setTokenValid(true)
      } else {
        addNotification({
          type: 'error',
          title: 'خطأ',
          message: 'رابط إعادة التعيين غير صحيح أو منتهي الصلاحية'
        })
      }
    } catch (err) {
      addNotification({
        type: 'error',
        title: 'خطأ في الاتصال',
        message: 'حدث خطأ أثناء التحقق من الرابط'
      })
    } finally {
      setVerifying(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)

    if (newPassword !== confirmPassword) {
      addNotification({
        type: 'error',
        title: 'خطأ في كلمة المرور',
        message: 'كلمة المرور الجديدة وتأكيدها غير متطابقين'
      })
      setLoading(false)
      return
    }

    try {
      const token = searchParams.get('token')
      const response = await fetch('/api/auth/reset-password', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ token, newPassword }),
      })

      const data = await response.json()

      if (response.ok) {
        addNotification({
          type: 'success',
          title: 'تم تغيير كلمة المرور',
          message: 'تم تغيير كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول'
        })
        router.push('/login')
      } else {
        addNotification({
          type: 'error',
          title: 'خطأ',
          message: data.error || 'فشل في تغيير كلمة المرور'
        })
      }
    } catch (err) {
      addNotification({
        type: 'error',
        title: 'خطأ في الاتصال',
        message: 'حدث خطأ أثناء تغيير كلمة المرور'
      })
    } finally {
      setLoading(false)
    }
  }

  if (verifying) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <span className="text-white text-2xl">🔐</span>
          </div>
          <p className="text-gray-600">جاري التحقق من رابط إعادة التعيين...</p>
        </div>
      </div>
    )
  }

  if (!tokenValid) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 bg-gradient-to-r from-red-600 to-pink-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <span className="text-white text-2xl">❌</span>
          </div>
          <h1 className="text-2xl font-bold text-gray-900 mb-4">رابط غير صحيح</h1>
          <p className="text-gray-600 mb-6">رابط إعادة التعيين غير صحيح أو منتهي الصلاحية</p>
          <button
            onClick={() => router.push('/login')}
            className="bg-gradient-to-r from-blue-600 to-purple-600 text-white font-semibold py-3 px-6 rounded-lg shadow-md hover:from-blue-700 hover:to-purple-700 transition-all duration-200"
          >
            العودة لتسجيل الدخول
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 flex items-center justify-center">
      <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl border border-gray-200/50 p-8 w-full max-w-md">
        <h1 className="text-3xl font-bold text-gray-900 text-center mb-6">إعادة تعيين كلمة المرور</h1>
        <p className="text-gray-600 text-center mb-6">
          أدخل كلمة المرور الجديدة
        </p>
        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label htmlFor="newPassword" className="block text-sm font-medium text-gray-700 mb-2">
              كلمة المرور الجديدة
            </label>
            <input
              type="password"
              id="newPassword"
              value={newPassword}
              onChange={(e) => setNewPassword(e.target.value)}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              required
            />
          </div>
          <div>
            <label htmlFor="confirmPassword" className="block text-sm font-medium text-gray-700 mb-2">
              تأكيد كلمة المرور الجديدة
            </label>
            <input
              type="password"
              id="confirmPassword"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              required
            />
          </div>
          <button
            type="submit"
            className="w-full bg-gradient-to-r from-blue-600 to-purple-600 text-white font-semibold py-3 rounded-lg shadow-md hover:from-blue-700 hover:to-purple-700 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
            disabled={loading}
          >
            {loading ? 'جاري التغيير...' : 'تغيير كلمة المرور'}
          </button>
          <button
            type="button"
            onClick={() => router.push('/login')}
            className="w-full text-gray-600 font-semibold py-3 rounded-lg hover:bg-gray-100 transition-all duration-200"
          >
            العودة لتسجيل الدخول
          </button>
        </form>
      </div>
    </div>
  )
}

export default function ResetPasswordPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <span className="text-white text-2xl">🔐</span>
          </div>
          <p className="text-gray-600">جاري التحميل...</p>
        </div>
      </div>
    }>
      <ResetPasswordContent />
    </Suspense>
  )
}

// frontend/src/app/pages/reset-password/reset-password.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule, ActivatedRoute } from '@angular/router';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-reset-password',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  template: `
    <div class="min-h-screen bg-gradient-to-br from-indigo-900 via-purple-800 to-pink-700 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
      <div class="max-w-md w-full space-y-8">
        <!-- Header -->
        <div class="text-center">
          <div class="mx-auto h-16 w-16 bg-white rounded-full flex items-center justify-center shadow-lg">
            <span class="text-3xl">🔑</span>
          </div>
          <h2 class="mt-6 text-3xl font-extrabold text-white">
            إعادة تعيين كلمة المرور
          </h2>
          <p class="mt-2 text-sm text-indigo-100">
            أدخل كلمة المرور الجديدة
          </p>
        </div>

        <!-- Reset Password Form -->
        <div class="bg-white rounded-2xl shadow-2xl p-8 space-y-6">
          <form (ngSubmit)="onSubmit()" #resetForm="ngForm" class="space-y-6">
            <!-- New Password Field -->
            <div>
              <label for="password" class="block text-sm font-medium text-gray-700 mb-2">
                كلمة المرور الجديدة
              </label>
              <div class="relative">
                <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                  <i class="fas fa-lock text-gray-400"></i>
                </div>
                <input
                  id="password"
                  name="password"
                  type="password"
                  [(ngModel)]="resetData.password"
                  required
                  minlength="6"
                  class="appearance-none relative block w-full pr-10 pl-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  placeholder="أدخل كلمة المرور الجديدة">
              </div>
            </div>

            <!-- Confirm Password Field -->
            <div>
              <label for="confirmPassword" class="block text-sm font-medium text-gray-700 mb-2">
                تأكيد كلمة المرور
              </label>
              <div class="relative">
                <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                  <i class="fas fa-lock text-gray-400"></i>
                </div>
                <input
                  id="confirmPassword"
                  name="confirmPassword"
                  type="password"
                  [(ngModel)]="resetData.confirmPassword"
                  required
                  class="appearance-none relative block w-full pr-10 pl-3 py-3 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  placeholder="أعد إدخال كلمة المرور الجديدة">
              </div>
            </div>

            <!-- Password Strength Indicator -->
            <div *ngIf="resetData.password" class="space-y-2">
              <div class="text-sm text-gray-600">قوة كلمة المرور:</div>
              <div class="w-full bg-gray-200 rounded-full h-2">
                <div class="h-2 rounded-full transition-all duration-300" 
                     [ngClass]="getPasswordStrengthClass()"
                     [style.width.%]="getPasswordStrength()"></div>
              </div>
              <div class="text-xs text-gray-500">
                <div *ngIf="resetData.password.length < 6" class="text-red-500">
                  كلمة المرور يجب أن تكون 6 أحرف على الأقل
                </div>
                <div *ngIf="resetData.password.length >= 6 && !hasUpperCase()" class="text-yellow-500">
                  أضف حرف كبير واحد على الأقل
                </div>
                <div *ngIf="resetData.password.length >= 6 && hasUpperCase() && !hasNumber()" class="text-yellow-500">
                  أضف رقم واحد على الأقل
                </div>
                <div *ngIf="resetData.password.length >= 6 && hasUpperCase() && hasNumber()" class="text-green-500">
                  كلمة مرور قوية
                </div>
              </div>
            </div>

            <!-- Error Message -->
            <div *ngIf="errorMessage" class="bg-red-50 border border-red-200 text-red-600 px-4 py-3 rounded-lg text-sm">
              <i class="fas fa-exclamation-circle mr-2"></i>
              {{ errorMessage }}
            </div>

            <!-- Success Message -->
            <div *ngIf="successMessage" class="bg-green-50 border border-green-200 text-green-600 px-4 py-3 rounded-lg text-sm">
              <i class="fas fa-check-circle mr-2"></i>
              {{ successMessage }}
            </div>

            <!-- Submit Button -->
            <div>
              <button
                type="submit"
                [disabled]="resetForm.invalid || isLoading || !passwordsMatch()"
                class="group relative w-full flex justify-center py-3 px-4 border border-transparent text-sm font-medium rounded-lg text-white bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 transform hover:scale-105">
                <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                  <i *ngIf="!isLoading" class="fas fa-key text-indigo-500 group-hover:text-indigo-400"></i>
                  <i *ngIf="isLoading" class="fas fa-spinner fa-spin text-indigo-500"></i>
                </span>
                {{ isLoading ? 'جاري إعادة التعيين...' : 'إعادة تعيين كلمة المرور' }}
              </button>
            </div>

            <!-- Back to Login -->
            <div class="text-center">
              <p class="text-sm text-gray-600">
                تذكرت كلمة المرور؟
                <a href="/login" class="font-medium text-indigo-600 hover:text-indigo-500 transition-colors">
                  العودة لتسجيل الدخول
                </a>
              </p>
            </div>
          </form>
        </div>

        <!-- Security Tips -->
        <div class="bg-white/10 backdrop-blur-sm rounded-2xl p-6 text-center">
          <h3 class="text-lg font-medium text-white mb-2">نصائح أمان كلمة المرور</h3>
          <ul class="text-sm text-indigo-100 space-y-1">
            <li>• استخدم مزيج من الأحرف الكبيرة والصغيرة</li>
            <li>• أضف أرقام ورموز خاصة</li>
            <li>• تجنب استخدام المعلومات الشخصية</li>
            <li>• لا تستخدم نفس كلمة المرور في مواقع أخرى</li>
          </ul>
        </div>

        <!-- Footer -->
        <div class="text-center">
          <p class="text-xs text-indigo-100">
            © 2024 نظام إدارة العقارات. جميع الحقوق محفوظة.
          </p>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .animate-fade-in {
      animation: fadeIn 0.6s ease-in-out;
    }
    @keyframes fadeIn {
      from { opacity: 0; transform: translateY(20px); }
      to { opacity: 1; transform: translateY(0); }
    }
  `]
})
export class ResetPasswordComponent implements OnInit {
  resetData = {
    password: '',
    confirmPassword: ''
  };
  isLoading = false;
  errorMessage = '';
  successMessage = '';
  token = '';

  constructor(
    private apiService: ApiService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit() {
    // Get token from URL parameters
    this.route.queryParams.subscribe(params => {
      this.token = params['token'] || '';
      if (!this.token) {
        this.errorMessage = 'رابط إعادة التعيين غير صحيح';
      }
    });

    // Check if user is already logged in
    const authToken = localStorage.getItem('auth_token');
    if (authToken) {
      this.router.navigate(['/']);
    }
  }

  passwordsMatch(): boolean {
    return this.resetData.password === this.resetData.confirmPassword;
  }

  hasUpperCase(): boolean {
    return /[A-Z]/.test(this.resetData.password);
  }

  hasNumber(): boolean {
    return /\d/.test(this.resetData.password);
  }

  getPasswordStrength(): number {
    let strength = 0;
    if (this.resetData.password.length >= 6) strength += 25;
    if (this.resetData.password.length >= 8) strength += 25;
    if (this.hasUpperCase()) strength += 25;
    if (this.hasNumber()) strength += 25;
    return strength;
  }

  getPasswordStrengthClass(): string {
    const strength = this.getPasswordStrength();
    if (strength < 50) return 'bg-red-500';
    if (strength < 75) return 'bg-yellow-500';
    return 'bg-green-500';
  }

  onSubmit() {
    if (this.isLoading) return;

    if (!this.passwordsMatch()) {
      this.errorMessage = 'كلمات المرور غير متطابقة';
      return;
    }

    if (this.resetData.password.length < 6) {
      this.errorMessage = 'كلمة المرور يجب أن تكون 6 أحرف على الأقل';
      return;
    }

    this.isLoading = true;
    this.errorMessage = '';
    this.successMessage = '';

    // Simulate API call (replace with actual reset password service)
    setTimeout(() => {
      // Mock reset password logic
      if (this.token && this.resetData.password) {
        this.successMessage = 'تم إعادة تعيين كلمة المرور بنجاح! يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.';
        
        // Redirect to login after 3 seconds
        setTimeout(() => {
          this.router.navigate(['/login']);
        }, 3000);
      } else {
        this.errorMessage = 'حدث خطأ أثناء إعادة تعيين كلمة المرور. يرجى المحاولة مرة أخرى.';
      }
      
      this.isLoading = false;
    }, 2000);
  }
}
