// frontend/src/app/pages/partners/partners.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-partners',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule],
  template: `
    <div class="space-y-6">
      <!-- Header -->
      <div class="flex items-center justify-between">
        <div>
          <h1 class="text-2xl font-bold text-gray-900">إدارة الشركاء</h1>
          <p class="text-gray-600">إدارة الشركاء والمجموعات</p>
        </div>
        <div class="flex gap-2">
          <button 
            class="btn btn-primary"
            (click)="openAddModal()">
            + شريك جديد
          </button>
          <button 
            class="btn btn-secondary"
            (click)="openGroupModal()">
            + مجموعة جديدة
          </button>
        </div>
      </div>

      <!-- Stats Cards -->
      <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div class="kpi-card">
          <div class="flex items-center justify-between">
            <div class="flex-1">
              <p class="text-xs font-medium text-gray-600 mb-1">إجمالي الشركاء</p>
              <p class="text-lg font-bold text-blue-600">{{ stats.total_partners || 0 }}</p>
            </div>
            <div class="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center">
              <span class="text-sm">👥</span>
            </div>
          </div>
        </div>

        <div class="kpi-card">
          <div class="flex items-center justify-between">
            <div class="flex-1">
              <p class="text-xs font-medium text-gray-600 mb-1">الشركاء النشطين</p>
              <p class="text-lg font-bold text-green-600">{{ stats.active_partners || 0 }}</p>
            </div>
            <div class="w-8 h-8 bg-green-100 rounded-lg flex items-center justify-center">
              <span class="text-sm">✅</span>
            </div>
          </div>
        </div>

        <div class="kpi-card">
          <div class="flex items-center justify-between">
            <div class="flex-1">
              <p class="text-xs font-medium text-gray-600 mb-1">الشركاء غير النشطين</p>
              <p class="text-lg font-bold text-red-600">{{ stats.inactive_partners || 0 }}</p>
            </div>
            <div class="w-8 h-8 bg-red-100 rounded-lg flex items-center justify-center">
              <span class="text-sm">❌</span>
            </div>
          </div>
        </div>

        <div class="kpi-card">
          <div class="flex items-center justify-between">
            <div class="flex-1">
              <p class="text-xs font-medium text-gray-600 mb-1">المجموعات</p>
              <p class="text-lg font-bold text-purple-600">{{ stats.total_groups || 0 }}</p>
            </div>
            <div class="w-8 h-8 bg-purple-100 rounded-lg flex items-center justify-center">
              <span class="text-sm">📁</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Tabs -->
      <div class="card">
        <div class="border-b border-gray-200">
          <nav class="-mb-px flex space-x-8">
            <button 
              class="py-2 px-1 border-b-2 font-medium text-sm"
              [ngClass]="activeTab === 'partners' ? 'border-blue-500 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700'"
              (click)="setActiveTab('partners')">
              الشركاء
            </button>
            <button 
              class="py-2 px-1 border-b-2 font-medium text-sm"
              [ngClass]="activeTab === 'groups' ? 'border-blue-500 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700'"
              (click)="setActiveTab('groups')">
              المجموعات
            </button>
          </nav>
        </div>
      </div>

      <!-- Partners Tab -->
      <div *ngIf="activeTab === 'partners'">
        <!-- Filters -->
        <div class="card">
          <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">البحث</label>
              <input 
                type="text" 
                class="input"
                placeholder="البحث بالاسم أو الهاتف..."
                [(ngModel)]="filters.search"
                (input)="onSearch()">
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">المجموعة</label>
              <select 
                class="input"
                [(ngModel)]="filters.group_id"
                (change)="onFilterChange()">
                <option value="">جميع المجموعات</option>
                <option *ngFor="let group of groups" [value]="group.id">
                  {{ group.name }}
                </option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">الحالة</label>
              <select 
                class="input"
                [(ngModel)]="filters.status"
                (change)="onFilterChange()">
                <option value="">جميع الحالات</option>
                <option value="active">نشط</option>
                <option value="inactive">غير نشط</option>
              </select>
            </div>
            <div class="flex items-end">
              <button 
                class="btn btn-secondary w-full"
                (click)="resetFilters()">
                إعادة تعيين
              </button>
            </div>
          </div>
        </div>

        <!-- Partners Table -->
        <div class="card p-0 overflow-hidden">
          <div class="overflow-x-auto">
            <table class="table">
              <thead>
                <tr>
                  <th>الاسم</th>
                  <th>الهاتف</th>
                  <th>الهوية الوطنية</th>
                  <th>المجموعات</th>
                  <th>الحالة</th>
                  <th>الإجراءات</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let partner of partners" class="animate-fade-in">
                  <td class="font-medium">{{ partner.name }}</td>
                  <td>{{ partner.phone || '-' }}</td>
                  <td>{{ partner.national_id || '-' }}</td>
                  <td>
                    <div class="flex flex-wrap gap-1">
                      <span 
                        *ngFor="let group of partner.groups" 
                        class="px-2 py-1 text-xs bg-blue-100 text-blue-800 rounded-full">
                        {{ group.name }}
                      </span>
                      <span *ngIf="!partner.groups?.length" class="text-gray-400 text-sm">-</span>
                    </div>
                  </td>
                  <td>
                    <span 
                      class="px-2 py-1 text-xs rounded-full"
                      [ngClass]="partner.status === 'active' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'">
                      {{ partner.status_label }}
                    </span>
                  </td>
                  <td>
                    <div class="flex gap-2">
                      <button 
                        class="btn btn-secondary text-xs"
                        (click)="editPartner(partner)">
                        تعديل
                      </button>
                      <button 
                        class="btn btn-danger text-xs"
                        (click)="deletePartner(partner)">
                        حذف
                      </button>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Groups Tab -->
      <div *ngIf="activeTab === 'groups'">
        <!-- Groups Table -->
        <div class="card p-0 overflow-hidden">
          <div class="overflow-x-auto">
            <table class="table">
              <thead>
                <tr>
                  <th>اسم المجموعة</th>
                  <th>الوصف</th>
                  <th>عدد الشركاء</th>
                  <th>تاريخ الإنشاء</th>
                  <th>الإجراءات</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let group of groups" class="animate-fade-in">
                  <td class="font-medium">{{ group.name }}</td>
                  <td class="max-w-xs truncate">{{ group.description || '-' }}</td>
                  <td>
                    <span class="px-2 py-1 text-xs bg-blue-100 text-blue-800 rounded-full">
                      {{ group.partners_count }} شريك
                    </span>
                  </td>
                  <td>{{ formatDate(group.created_at) }}</td>
                  <td>
                    <div class="flex gap-2">
                      <button 
                        class="btn btn-secondary text-xs"
                        (click)="editGroup(group)">
                        تعديل
                      </button>
                      <button 
                        class="btn btn-danger text-xs"
                        (click)="deleteGroup(group)">
                        حذف
                      </button>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Add/Edit Partner Modal -->
      <div *ngIf="showPartnerModal" class="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
        <div class="bg-white rounded-xl shadow-2xl w-full max-w-2xl animate-scale-in">
          <div class="p-6 border-b border-gray-200">
            <h3 class="text-lg font-semibold text-gray-900">
              {{ editingPartner ? 'تعديل الشريك' : 'شريك جديد' }}
            </h3>
          </div>
          
          <form [formGroup]="partnerForm" (ngSubmit)="onPartnerSubmit()" class="p-6 space-y-4">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">الاسم *</label>
                <input 
                  type="text" 
                  class="input"
                  formControlName="name"
                  placeholder="اسم الشريك">
                <div *ngIf="partnerForm.get('name')?.invalid && partnerForm.get('name')?.touched" 
                     class="text-red-500 text-xs mt-1">
                  الاسم مطلوب
                </div>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">الهاتف</label>
                <input 
                  type="text" 
                  class="input"
                  formControlName="phone"
                  placeholder="رقم الهاتف">
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">الهوية الوطنية</label>
                <input 
                  type="text" 
                  class="input"
                  formControlName="national_id"
                  placeholder="رقم الهوية الوطنية">
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">الحالة</label>
                <select class="input" formControlName="status">
                  <option value="active">نشط</option>
                  <option value="inactive">غير نشط</option>
                </select>
              </div>

              <div class="md:col-span-2">
                <label class="block text-sm font-medium text-gray-700 mb-2">العنوان</label>
                <textarea 
                  class="input"
                  formControlName="address"
                  placeholder="عنوان الشريك"
                  rows="2"></textarea>
              </div>

              <div class="md:col-span-2">
                <label class="block text-sm font-medium text-gray-700 mb-2">المجموعات</label>
                <div class="grid grid-cols-2 gap-2 max-h-32 overflow-y-auto border border-gray-200 rounded-lg p-2">
                  <label *ngFor="let group of groups" class="flex items-center space-x-2 text-sm">
                    <input 
                      type="checkbox" 
                      [value]="group.id"
                      (change)="onGroupToggle(group.id, $event)">
                    <span>{{ group.name }}</span>
                  </label>
                </div>
              </div>

              <div class="md:col-span-2">
                <label class="block text-sm font-medium text-gray-700 mb-2">ملاحظات</label>
                <textarea 
                  class="input"
                  formControlName="notes"
                  placeholder="ملاحظات إضافية"
                  rows="3"></textarea>
              </div>
            </div>

            <div class="flex gap-3 pt-4">
              <button 
                type="submit" 
                class="btn btn-primary flex-1"
                [disabled]="partnerForm.invalid || submitting">
                {{ submitting ? 'جاري الحفظ...' : (editingPartner ? 'تحديث' : 'إضافة') }}
              </button>
              <button 
                type="button" 
                class="btn btn-secondary"
                (click)="closePartnerModal()">
                إلغاء
              </button>
            </div>
          </form>
        </div>
      </div>

      <!-- Add/Edit Group Modal -->
      <div *ngIf="showGroupModal" class="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
        <div class="bg-white rounded-xl shadow-2xl w-full max-w-lg animate-scale-in">
          <div class="p-6 border-b border-gray-200">
            <h3 class="text-lg font-semibold text-gray-900">
              {{ editingGroup ? 'تعديل المجموعة' : 'مجموعة جديدة' }}
            </h3>
          </div>
          
          <form [formGroup]="groupForm" (ngSubmit)="onGroupSubmit()" class="p-6 space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">اسم المجموعة *</label>
              <input 
                type="text" 
                class="input"
                formControlName="name"
                placeholder="اسم المجموعة">
              <div *ngIf="groupForm.get('name')?.invalid && groupForm.get('name')?.touched" 
                   class="text-red-500 text-xs mt-1">
                اسم المجموعة مطلوب
              </div>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">الوصف</label>
              <textarea 
                class="input"
                formControlName="description"
                placeholder="وصف المجموعة"
                rows="3"></textarea>
            </div>

            <div class="flex gap-3 pt-4">
              <button 
                type="submit" 
                class="btn btn-primary flex-1"
                [disabled]="groupForm.invalid || submitting">
                {{ submitting ? 'جاري الحفظ...' : (editingGroup ? 'تحديث' : 'إضافة') }}
              </button>
              <button 
                type="button" 
                class="btn btn-secondary"
                (click)="closeGroupModal()">
                إلغاء
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `,
  styles: []
})
export class PartnersComponent implements OnInit {
  partners: any[] = [];
  groups: any[] = [];
  loading = false;
  error: string | null = null;
  showPartnerModal = false;
  showGroupModal = false;
  editingPartner: any = null;
  editingGroup: any = null;
  submitting = false;
  activeTab = 'partners';
  
  stats: any = {};
  
  filters: any = {
    search: '',
    group_id: '',
    status: '',
    page: 1,
    per_page: 15
  };

  partnerForm: FormGroup;
  groupForm: FormGroup;
  selectedGroups: number[] = [];

  constructor(
    private apiService: ApiService,
    private fb: FormBuilder
  ) {
    this.partnerForm = this.fb.group({
      name: ['', Validators.required],
      phone: [''],
      national_id: [''],
      address: [''],
      status: ['active'],
      notes: ['']
    });

    this.groupForm = this.fb.group({
      name: ['', Validators.required],
      description: ['']
    });
  }

  ngOnInit() {
    this.loadPartners();
    this.loadGroups();
    this.loadStats();
  }

  loadPartners() {
    this.loading = true;
    this.error = null;

    this.apiService.getPartners(this.filters).subscribe({
      next: (response) => {
        if (response.success) {
          this.partners = response.data;
        } else {
          this.error = 'فشل في تحميل الشركاء';
        }
        this.loading = false;
      },
      error: (error) => {
        this.error = 'خطأ في الاتصال بالخادم';
        this.loading = false;
        console.error('Partners error:', error);
      }
    });
  }

  loadGroups() {
    this.apiService.getPartnerGroups().subscribe({
      next: (response) => {
        if (response.success) {
          this.groups = response.data;
        }
      },
      error: (error) => {
        console.error('Groups error:', error);
      }
    });
  }

  loadStats() {
    this.apiService.getPartnerStats().subscribe({
      next: (response) => {
        if (response.success) {
          this.stats = response.data;
        }
      },
      error: (error) => {
        console.error('Stats error:', error);
      }
    });
  }

  setActiveTab(tab: string) {
    this.activeTab = tab;
  }

  onSearch() {
    this.filters.page = 1;
    this.loadPartners();
  }

  onFilterChange() {
    this.filters.page = 1;
    this.loadPartners();
  }

  resetFilters() {
    this.filters = {
      search: '',
      group_id: '',
      status: '',
      page: 1,
      per_page: 15
    };
    this.loadPartners();
  }

  openAddModal() {
    this.editingPartner = null;
    this.selectedGroups = [];
    this.partnerForm.reset({
      status: 'active'
    });
    this.showPartnerModal = true;
  }

  editPartner(partner: any) {
    this.editingPartner = partner;
    this.selectedGroups = partner.groups?.map((g: any) => g.id) || [];
    this.partnerForm.patchValue(partner);
    this.showPartnerModal = true;
  }

  closePartnerModal() {
    this.showPartnerModal = false;
    this.editingPartner = null;
    this.partnerForm.reset();
    this.selectedGroups = [];
  }

  openGroupModal() {
    this.editingGroup = null;
    this.groupForm.reset();
    this.showGroupModal = true;
  }

  editGroup(group: any) {
    this.editingGroup = group;
    this.groupForm.patchValue(group);
    this.showGroupModal = true;
  }

  closeGroupModal() {
    this.showGroupModal = false;
    this.editingGroup = null;
    this.groupForm.reset();
  }

  onGroupToggle(groupId: number, event: any) {
    if (event.target.checked) {
      this.selectedGroups.push(groupId);
    } else {
      this.selectedGroups = this.selectedGroups.filter(id => id !== groupId);
    }
  }

  onPartnerSubmit() {
    if (this.partnerForm.invalid) return;

    this.submitting = true;
    const formData = {
      ...this.partnerForm.value,
      groups: this.selectedGroups
    };

    const operation = this.editingPartner 
      ? this.apiService.updatePartner(this.editingPartner.id, formData)
      : this.apiService.createPartner(formData);

    operation.subscribe({
      next: (response) => {
        if (response.success) {
          this.closePartnerModal();
          this.loadPartners();
          this.loadStats();
        } else {
          this.error = 'فشل في حفظ الشريك';
        }
        this.submitting = false;
      },
      error: (error) => {
        this.error = 'خطأ في الاتصال بالخادم';
        this.submitting = false;
        console.error('Save partner error:', error);
      }
    });
  }

  onGroupSubmit() {
    if (this.groupForm.invalid) return;

    this.submitting = true;
    const formData = this.groupForm.value;

    const operation = this.editingGroup 
      ? this.apiService.updatePartnerGroup(this.editingGroup.id, formData)
      : this.apiService.createPartnerGroup(formData);

    operation.subscribe({
      next: (response) => {
        if (response.success) {
          this.closeGroupModal();
          this.loadGroups();
          this.loadStats();
        } else {
          this.error = 'فشل في حفظ المجموعة';
        }
        this.submitting = false;
      },
      error: (error) => {
        this.error = 'خطأ في الاتصال بالخادم';
        this.submitting = false;
        console.error('Save group error:', error);
      }
    });
  }

  deletePartner(partner: any) {
    if (confirm(`هل أنت متأكد من حذف الشريك "${partner.name}"؟`)) {
      this.apiService.deletePartner(partner.id).subscribe({
        next: (response) => {
          if (response.success) {
            this.loadPartners();
            this.loadStats();
          } else {
            this.error = 'فشل في حذف الشريك';
          }
        },
        error: (error) => {
          this.error = 'خطأ في الاتصال بالخادم';
          console.error('Delete partner error:', error);
        }
      });
    }
  }

  deleteGroup(group: any) {
    if (confirm(`هل أنت متأكد من حذف المجموعة "${group.name}"؟`)) {
      this.apiService.deletePartnerGroup(group.id).subscribe({
        next: (response) => {
          if (response.success) {
            this.loadGroups();
            this.loadStats();
          } else {
            this.error = 'فشل في حذف المجموعة';
          }
        },
        error: (error) => {
          this.error = 'خطأ في الاتصال بالخادم';
          console.error('Delete group error:', error);
        }
      });
    }
  }

  formatDate(date: string): string {
    return new Date(date).toLocaleDateString('ar-SA');
  }
}

// src/app/partners/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { Partner } from '@/types'
import { formatDate } from '@/utils/formatting'
import { checkDuplicateName, checkDuplicatePhone } from '@/utils/duplicateCheck'
import { NotificationSystem, useNotifications } from '@/components/NotificationSystem'
import SidebarToggle from '@/components/SidebarToggle'
import Sidebar from '@/components/Sidebar'
import NavigationButtons from '@/components/NavigationButtons'

// Modern UI Components
const ModernCard = ({ children, className = '', ...props }: any) => (
  <div className={`bg-white/80 backdrop-blur-sm border border-gray-200/50 rounded-2xl shadow-xl shadow-gray-900/5 p-6 ${className}`} {...props}>
    {children}
  </div>
)

const ModernButton = ({ children, variant = 'primary', size = 'md', className = '', ...props }: any) => {
  const variants: { [key: string]: string } = {
    primary: 'bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg shadow-blue-500/25',
    secondary: 'bg-white/80 hover:bg-white border border-gray-200 text-gray-700 shadow-lg shadow-gray-900/5',
    success: 'bg-gradient-to-r from-green-600 to-green-700 hover:from-green-700 hover:to-green-800 text-white shadow-lg shadow-green-500/25',
    danger: 'bg-gradient-to-r from-red-600 to-red-700 hover:from-red-700 hover:to-red-800 text-white shadow-lg shadow-red-500/25',
    warning: 'bg-gradient-to-r from-yellow-600 to-yellow-700 hover:from-yellow-700 hover:to-yellow-800 text-white shadow-lg shadow-yellow-500/25',
    info: 'bg-gradient-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800 text-white shadow-lg shadow-purple-500/25'
  }
  
  const sizes: { [key: string]: string } = {
    sm: 'px-3 py-2 text-sm',
    md: 'px-4 py-2.5 text-sm font-medium',
    lg: 'px-6 py-3 text-base font-medium'
  }
  
  return (
    <button 
      className={`${variants[variant]} ${sizes[size]} rounded-xl transition-all duration-200 hover:scale-105 active:scale-95 ${className}`}
      {...props}
    >
      {children}
    </button>
  )
}

const ModernInput = ({ label, className = '', ...props }: any) => (
  <div className="space-y-2">
    {label && <label className="text-sm font-bold text-gray-900">{label}</label>}
    <input 
      className={`w-full px-4 py-3 bg-white/80 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all duration-200 text-gray-900 font-bold placeholder:text-gray-500 placeholder:font-normal ${className}`}
      {...props}
    />
  </div>
)

const ModernTextarea = ({ label, className = '', ...props }: any) => (
  <div className="space-y-2">
    {label && <label className="text-sm font-bold text-gray-900">{label}</label>}
    <textarea 
      className={`w-full px-4 py-3 bg-white/80 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all duration-200 text-gray-900 font-bold placeholder:text-gray-500 placeholder:font-normal resize-none ${className}`}
      {...props}
    />
  </div>
)

export default function Partners() {
  const [partners, setPartners] = useState<Partner[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState<string | null>(null)
  const [search, setSearch] = useState('')
  const [showAddForm, setShowAddForm] = useState(false)
  const [deletingPartners, setDeletingPartners] = useState<Set<string>>(new Set())
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [newPartner, setNewPartner] = useState({
    name: '',
    phone: '',
    notes: ''
  })
  const [editingPartner, setEditingPartner] = useState<Partner | null>(null)
  const [showEditForm, setShowEditForm] = useState(false)
  
  const router = useRouter()
  const { notifications, addNotification, removeNotification } = useNotifications()

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyPress = (e: KeyboardEvent) => {
      // Only handle shortcuts when not in input fields
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement || e.target instanceof HTMLSelectElement) {
        return
      }

      if (e.ctrlKey || e.metaKey) {
        switch (e.key) {
          case 'b':
            e.preventDefault()
            setSidebarOpen(!sidebarOpen)
            break
          case 'f':
            e.preventDefault()
            document.getElementById('search-input')?.focus()
            break
          case 'Escape':
            e.preventDefault()
            setSearch('')
            setShowAddForm(false)
            setShowEditForm(false)
            break
        }
      }
    }

    document.addEventListener('keydown', handleKeyPress)
    return () => document.removeEventListener('keydown', handleKeyPress)
  }, [sidebarOpen])

  useEffect(() => {
    const token = localStorage.getItem('authToken')
    if (!token) {
      router.push('/login')
      return
    }
    
    fetchPartners()
  }, [])

  const fetchPartners = async () => {
    try {
      const token = localStorage.getItem('authToken')
      const response = await fetch('/api/partners', {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      })

      if (!response.ok) {
        if (response.status === 401) {
          localStorage.removeItem('authToken')
          router.push('/login')
          return
        }
        throw new Error('فشل في تحميل الشركاء')
      }

      const data = await response.json()
      if (data.success) {
        setPartners(data.data || [])
        setError(null)
      } else {
        setError(data.error || 'خطأ في تحميل الشركاء')
        addNotification({
          type: 'error',
          title: 'خطأ في التحميل',
          message: data.error || 'فشل في تحميل الشركاء'
        })
      }
    } catch (err) {
      console.error('Partners error:', err)
      setError('خطأ في الاتصال')
      addNotification({
        type: 'error',
        title: 'خطأ في الاتصال',
        message: 'فشل في الاتصال بالخادم'
      })
    } finally {
      setLoading(false)
    }
  }

  const handleAddPartner = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!newPartner.name.trim()) {
      setError('الرجاء إدخال اسم الشريك')
      addNotification({
        type: 'error',
        title: 'خطأ في البيانات',
        message: 'الرجاء إدخال اسم الشريك'
      })
      return
    }

    // فحص تكرار الاسم
    if (checkDuplicateName(newPartner.name, partners)) {
      setError('اسم الشريك موجود بالفعل')
      addNotification({
        type: 'error',
        title: 'خطأ في البيانات',
        message: 'اسم الشريك موجود بالفعل'
      })
      return
    }

    // فحص تكرار رقم الهاتف (إذا تم إدخاله)
    if (newPartner.phone && checkDuplicatePhone(newPartner.phone, partners)) {
      setError('رقم الهاتف موجود بالفعل')
      addNotification({
        type: 'error',
        title: 'خطأ في البيانات',
        message: 'رقم الهاتف موجود بالفعل'
      })
      return
    }

    try {
      const token = localStorage.getItem('authToken')
      const response = await fetch('/api/partners', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(newPartner)
      })

      if (!response.ok) {
        throw new Error('فشل في إضافة الشريك')
      }

      const data = await response.json()
      if (data.success) {
        setShowAddForm(false)
        setSuccess('تم إضافة الشريك بنجاح!')
        setError(null)
        setNewPartner({
          name: '',
          phone: '',
          notes: ''
        })
        fetchPartners()
        addNotification({
          type: 'success',
          title: 'تم الإضافة بنجاح',
          message: 'تم إضافة الشريك بنجاح'
        })
      } else {
        setError(data.error || 'خطأ في إضافة الشريك')
        setSuccess(null)
        addNotification({
          type: 'error',
          title: 'خطأ في الإضافة',
          message: data.error || 'فشل في إضافة الشريك'
        })
      }
    } catch (err) {
      console.error('Add partner error:', err)
      setError('خطأ في إضافة الشريك')
      setSuccess(null)
      addNotification({
        type: 'error',
        title: 'خطأ في الإضافة',
        message: 'فشل في إضافة الشريك'
      })
    }
  }

  const handleEditPartner = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!editingPartner || !editingPartner.name.trim()) {
      setError('الرجاء إدخال اسم الشريك')
      return
    }

    try {
      const token = localStorage.getItem('authToken')
      const response = await fetch(`/api/partners/${editingPartner.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          name: editingPartner.name,
          phone: editingPartner.phone,
          notes: editingPartner.notes
        })
      })

      if (!response.ok) {
        throw new Error('فشل في تحديث الشريك')
      }

      const data = await response.json()
      if (data.success) {
        setShowEditForm(false)
        setEditingPartner(null)
        setSuccess('تم تحديث الشريك بنجاح!')
        setError(null)
        fetchPartners()
        addNotification({
          type: 'success',
          title: 'تم التحديث بنجاح',
          message: 'تم تحديث الشريك بنجاح'
        })
      } else {
        setError(data.error || 'خطأ في تحديث الشريك')
        setSuccess(null)
        addNotification({
          type: 'error',
          title: 'خطأ في التحديث',
          message: data.error || 'فشل في تحديث الشريك'
        })
      }
    } catch (err) {
      console.error('Edit partner error:', err)
      setError('خطأ في تحديث الشريك')
      setSuccess(null)
      addNotification({
        type: 'error',
        title: 'خطأ في التحديث',
        message: 'فشل في تحديث الشريك'
      })
    }
  }

  const handleDeletePartner = async (partnerId: string) => {
    if (!confirm('هل أنت متأكد من حذف هذا الشريك؟')) return

    try {
      setDeletingPartners(prev => new Set(prev).add(partnerId))
      const token = localStorage.getItem('authToken')
      const response = await fetch(`/api/partners/${partnerId}`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${token}` }
      })

      const data = await response.json()
      if (data.success) {
        setSuccess('تم حذف الشريك بنجاح!')
        setError(null)
        fetchPartners()
        addNotification({
          type: 'success',
          title: 'تم الحذف بنجاح',
          message: 'تم حذف الشريك بنجاح'
        })
      } else {
        setError(data.error || 'خطأ في حذف الشريك')
        setSuccess(null)
        addNotification({
          type: 'error',
          title: 'خطأ في الحذف',
          message: data.error || 'فشل في حذف الشريك'
        })
      }
    } catch (err) {
      console.error('Delete partner error:', err)
      setError('خطأ في حذف الشريك')
      setSuccess(null)
      addNotification({
        type: 'error',
        title: 'خطأ في الحذف',
        message: 'فشل في حذف الشريك'
      })
    } finally {
      setDeletingPartners(prev => {
        const newSet = new Set(prev)
        newSet.delete(partnerId)
        return newSet
      })
    }
  }

  const startEdit = (partner: Partner) => {
    setEditingPartner({ ...partner })
    setShowEditForm(true)
    setShowAddForm(false)
  }

  const filteredPartners = partners.filter(partner => 
    search === '' || 
    partner.name.toLowerCase().includes(search.toLowerCase()) ||
    (partner.phone && partner.phone.toLowerCase().includes(search.toLowerCase())) ||
    (partner.notes && partner.notes.toLowerCase().includes(search.toLowerCase()))
  )

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <h2 className="text-xl font-semibold text-gray-700">جاري التحميل...</h2>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      {/* Sidebar */}
      <Sidebar isOpen={sidebarOpen} onToggle={() => setSidebarOpen(!sidebarOpen)} />
      
      {/* Main Content */}
      <div className={`transition-all duration-300 ${sidebarOpen ? 'lg:mr-72' : ''}`}>
        {/* Header */}
        <div className="bg-white/80 backdrop-blur-sm border-b border-gray-200/50 sticky top-0 z-40">
          <div className="max-w-7xl mx-auto px-6 py-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-4 space-x-reverse">
                <SidebarToggle onToggle={() => setSidebarOpen(!sidebarOpen)} />
                <div className="w-12 h-12 bg-gradient-to-r from-blue-600 to-purple-600 rounded-xl flex items-center justify-center">
                  <span className="text-white text-xl">👥</span>
                </div>
                <div>
                  <h1 className="text-2xl font-bold text-gray-900">إدارة الشركاء</h1>
                  <p className="text-gray-600">نظام متطور لإدارة الشركاء والمستثمرين</p>
                </div>
              </div>
              <div className="flex items-center space-x-3 space-x-reverse">
                <ModernButton variant="secondary" onClick={() => router.push('/partner-debts')}>
                  💰 ديون الشركاء
                </ModernButton>
                <ModernButton variant="secondary" onClick={() => router.push('/partner-groups')}>
                  👥 مجموعات الشركاء
                </ModernButton>
                <NavigationButtons />
              </div>
            </div>
          </div>
        </div>

        {/* Main Content */}
        <div className="max-w-7xl mx-auto px-6 py-8">
        {/* Add Partner Form */}
        {showAddForm && (
          <ModernCard className="mb-8">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-bold text-gray-900">إضافة شريك جديد</h2>
              <button
                onClick={() => setShowAddForm(false)}
                className="w-10 h-10 bg-gray-100 hover:bg-gray-200 rounded-xl flex items-center justify-center transition-colors duration-200"
              >
                ✕
              </button>
            </div>

            {success && (
              <div className="mb-6 p-4 bg-green-50 border border-green-200 rounded-xl">
                <div className="flex items-center">
                  <span className="text-green-500 mr-2">✅</span>
                  <span className="text-green-700">{success}</span>
                </div>
              </div>
            )}

            {error && (
              <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-xl">
                <div className="flex items-center">
                  <span className="text-red-500 mr-2">⚠️</span>
                  <span className="text-red-700">{error}</span>
                </div>
              </div>
            )}

            <form onSubmit={handleAddPartner} className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <ModernInput
                  label="اسم الشريك *"
                  type="text"
                  value={newPartner.name}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => setNewPartner({...newPartner, name: e.target.value})}
                  placeholder="أدخل اسم الشريك"
                  required
                />
                
                <ModernInput
                  label="رقم الهاتف"
                  type="tel"
                  value={newPartner.phone}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => setNewPartner({...newPartner, phone: e.target.value})}
                  placeholder="أدخل رقم الهاتف"
                />
              </div>
              
              <ModernTextarea
                label="ملاحظات"
                value={newPartner.notes}
                onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setNewPartner({...newPartner, notes: e.target.value})}
                placeholder="أدخل أي ملاحظات إضافية"
                rows={3}
              />
              
              <div className="flex items-center justify-end space-x-3 space-x-reverse pt-6 border-t border-gray-200">
                <ModernButton variant="secondary" onClick={() => setShowAddForm(false)}>
                  إلغاء
                </ModernButton>
                <ModernButton type="submit">
                  <span className="mr-2">➕</span>
                  إضافة الشريك
                </ModernButton>
              </div>
            </form>
          </ModernCard>
        )}

        {/* Edit Partner Form */}
        {showEditForm && editingPartner && (
          <ModernCard className="mb-8">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-bold text-gray-900">تعديل الشريك</h2>
              <button
                onClick={() => setShowEditForm(false)}
                className="w-10 h-10 bg-gray-100 hover:bg-gray-200 rounded-xl flex items-center justify-center transition-colors duration-200"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleEditPartner} className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <ModernInput
                  label="اسم الشريك *"
                  type="text"
                  value={editingPartner.name}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEditingPartner({...editingPartner, name: e.target.value})}
                  placeholder="أدخل اسم الشريك"
                  required
                />
                
                <ModernInput
                  label="رقم الهاتف"
                  type="tel"
                  value={editingPartner.phone || ''}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEditingPartner({...editingPartner, phone: e.target.value})}
                  placeholder="أدخل رقم الهاتف"
                />
              </div>
              
              <ModernTextarea
                label="ملاحظات"
                value={editingPartner.notes || ''}
                onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setEditingPartner({...editingPartner, notes: e.target.value})}
                placeholder="أدخل أي ملاحظات إضافية"
                rows={3}
              />
              
              <div className="flex items-center justify-end space-x-3 space-x-reverse pt-6 border-t border-gray-200">
                <ModernButton variant="secondary" onClick={() => setShowEditForm(false)}>
                  إلغاء
                </ModernButton>
                <ModernButton type="submit">
                  <span className="mr-2">💾</span>
                  حفظ التغييرات
                </ModernButton>
              </div>
            </form>
          </ModernCard>
        )}

        {/* Search and Actions */}
        <ModernCard className="mb-8">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4 space-x-reverse">
              <div className="relative">
                <input
                  id="search-input"
                  type="text"
                  placeholder="🔍 ابحث في الشركاء... (Ctrl+F)"
                  value={search}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSearch(e.target.value)}
                  className="w-80 px-4 py-3 bg-white/80 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all duration-200"
                />
              </div>
            </div>
            <div className="flex items-center space-x-3 space-x-reverse">
              <ModernButton onClick={() => setShowAddForm(true)}>
                <span className="mr-2">➕</span>
                إضافة شريك جديد
              </ModernButton>
              <div className="text-sm text-gray-500">
                {filteredPartners.length} شريك
              </div>
            </div>
          </div>
        </ModernCard>

        {/* Partners List */}
        <ModernCard>
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-bold text-gray-900">قائمة الشركاء</h2>
            <div className="flex items-center space-x-2 space-x-reverse">
              <span className="text-sm text-gray-500">آخر تحديث:</span>
              <span className="text-sm font-medium text-gray-700">{new Date().toLocaleString('en-GB')}</span>
            </div>
          </div>

          {error && (
            <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-xl">
              <div className="flex items-center">
                <span className="text-red-500 mr-2">⚠️</span>
                <span className="text-red-700">{error}</span>
              </div>
            </div>
          )}

          {success && (
            <div className="mb-6 p-4 bg-green-50 border border-green-200 rounded-xl">
              <div className="flex items-center">
                <span className="text-green-500 mr-2">✅</span>
                <span className="text-green-700">{success}</span>
              </div>
            </div>
          )}

          {filteredPartners.length === 0 ? (
            <div className="text-center py-12">
              <div className="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-4xl text-gray-400">👥</span>
              </div>
              <h3 className="text-xl font-semibold text-gray-700 mb-2">لا توجد شركاء</h3>
              <p className="text-gray-500 mb-6">لم يتم إضافة أي شركاء بعد. ابدأ بإضافة شريك جديد</p>
              <ModernButton onClick={() => setShowAddForm(true)}>
                <span className="mr-2">➕</span>
                إضافة شريك جديد
              </ModernButton>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-gray-200">
                    <th className="text-right py-4 px-6 font-semibold text-gray-700">اسم الشريك</th>
                    <th className="text-right py-4 px-6 font-semibold text-gray-700">رقم الهاتف</th>
                    <th className="text-right py-4 px-6 font-semibold text-gray-700">ملاحظات</th>
                    <th className="text-right py-4 px-6 font-semibold text-gray-700">تاريخ الإضافة</th>
                    <th className="text-right py-4 px-6 font-semibold text-gray-700">الإجراءات</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredPartners.map((partner) => (
                    <tr 
                      key={partner.id} 
                      className="border-b border-gray-100 hover:bg-blue-50/50 transition-colors duration-150"
                    >
                      <td className="py-4 px-6">
                        <div className="font-medium text-gray-900">{partner.name}</div>
                      </td>
                      <td className="py-4 px-6">
                        <div className="text-gray-600">{partner.phone || '-'}</div>
                      </td>
                      <td className="py-4 px-6">
                        <div className="text-gray-600 max-w-xs truncate">{partner.notes || '-'}</div>
                      </td>
                      <td className="py-4 px-6">
                        <div className="text-gray-600">{partner.createdAt ? formatDate(partner.createdAt) : '-'}</div>
                      </td>
                      <td className="py-4 px-6">
                        <div className="flex items-center space-x-2 space-x-reverse">
                          <ModernButton 
                            size="sm" 
                            variant="info" 
                            onClick={() => router.push(`/partners/${partner.id}`)}
                          >
                            👁️ تفاصيل
                          </ModernButton>
                          <ModernButton 
                            size="sm" 
                            variant="warning" 
                            onClick={() => startEdit(partner)}
                          >
                            ✏️ تعديل
                          </ModernButton>
                          <ModernButton 
                            size="sm" 
                            variant="danger" 
                            onClick={() => handleDeletePartner(partner.id)}
                            disabled={deletingPartners.has(partner.id)}
                          >
                            {deletingPartners.has(partner.id) ? '⏳' : '🗑️'} حذف
                          </ModernButton>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </ModernCard>
        </div>
        
        <NotificationSystem 
          notifications={notifications} 
          onRemove={removeNotification} 
        />
      </div>
    </div>
  )
}
